In [13]:
import pandas as pd

In [14]:
shr = pd.Series([24,8,88])
shr

0    24
1     8
2    88
dtype: int64

In [15]:
a=pd.Series(["shi","shi", "r"])
a

0    shi
1    shi
2      r
dtype: object

In [16]:
b = pd.Series([24, 8, 88], index = ["day","month", "year"])
b

day      24
month     8
year     88
dtype: int64

In [17]:
type(b)

pandas.core.series.Series

In [18]:
import numpy as np

In [19]:
a =np.array(['sddf', 'shishir', 'abhi'])
print(a)

['sddf' 'shishir' 'abhi']


In [20]:
a[0]

'sddf'

In [21]:
a[1:2]

array(['shishir'], dtype='<U7')

In [22]:
b = np.array(range(1,10))
print(b)

[1 2 3 4 5 6 7 8 9]


In [23]:
pd.Series([1,10])

0     1
1    10
dtype: int64

In [24]:
np.array(range(1,10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.array(('shi', 'sjidfjs', 'hsdjfj'))

array(['shi', 'sjidfjs', 'hsdjfj'], dtype='<U7')

In [26]:
a = pd.Series(np.array(range(2,10)), index = range(0,8))
a

0    2
1    3
2    4
3    5
4    6
5    7
6    8
7    9
dtype: int32

In [27]:
pd.Series(range(1,15))

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
dtype: int64

In [28]:
a = pd.Series((1,2,3,4), index = (2,3,1,40))

In [29]:
a


2     1
3     2
1     3
40    4
dtype: int64

In [30]:
a = np.array((2,4,6))
b = np.array((2,2,2))
a*b

array([ 4,  8, 12])

In [31]:
a

array([2, 4, 6])

In [32]:
b

array([2, 2, 2])

In [33]:
a[2]

6

In [34]:
a+b

array([4, 6, 8])

In [35]:
a-b

array([0, 2, 4])

In [36]:
a==b

array([ True, False, False])

In [37]:
a>2

array([False,  True,  True])

In [38]:
a**b

array([ 4, 16, 36], dtype=int32)

In [44]:
a

array([2, 4, 6])

In [40]:
b

array([2, 2, 2])

In [45]:
a**10

array([    1024,  1048576, 60466176], dtype=int32)

In [42]:
2**10

1024

In [43]:
pd.Series([2,4,6,8], index = [1,1,1,1])

1    2
1    4
1    6
1    8
dtype: int64

In [61]:
a = pd.Series(['abhi', 24.1, 24, 2+0j])

In [62]:
a

0      abhi
1      24.1
2        24
3    (2+0j)
dtype: object

In [63]:
a[3]

(2+0j)

In [71]:
pd.DataFrame({'name':('a', 'b', 'c')})

name
0    a
1    b
2    c

In [46]:
df = pd.DataFrame({'name': ['Vinay', 'Kushal', 'Aman', 'Saif'], 
                   'age': [22, 25, 24, 28], 
                    'occupation': ['engineer', 'doctor', 'data analyst', 'teacher']})
df

name  age    occupation
0   Vinay   22      engineer
1  Kushal   25        doctor
2    Aman   24  data analyst
3    Saif   28       teacher

In [47]:
a = pd.DataFrame({'class': (1,2,3,4,5,6), 'students': (22,33,44,55,66,77),
                  'average marks': (45,45,45,67,7,8)})
a

class  students  average marks
0      1        22             45
1      2        33             45
2      3        44             45
3      4        55             67
4      5        66              7
5      6        77              8

In [48]:
import pandas as pd

In [49]:
aa = pd.DataFrame([[[12,12,12,12,12], [1,2,3,4,5]]])
aa

0                1
0  [12, 12, 12, 12, 12]  [1, 2, 3, 4, 5]

In [50]:
aa = pd.DataFrame([[12,12,12,12,12], [1,2,3,4,5]])
aa

0   1   2   3   4
0  12  12  12  12  12
1   1   2   3   4   5

In [51]:
aa = pd.DataFrame({'HDFC':[12,12,12,12,12],'code':[1,2,3,4,5]})
aa

HDFC  code
0    12     1
1    12     2
2    12     3
3    12     4
4    12     5

In [56]:
aa = pd.DataFrame([12,12,12,12,12], [1,2,3,4,5], columns=['HDFC'])
aa

HDFC
1    12
2    12
3    12
4    12
5    12

In [84]:
data = pd.DataFrame({'names': ('shr', 'kvm', 'chs'), 'EId':(12,13,14), 'Salary':(1000,1500,1600)})
data

names  EId  Salary
0   shr   12    1000
1   kvm   13    1500
2   chs   14    1600

In [65]:
data.iloc[1,2]

1500

In [81]:
data.iloc[:,-1] #reversing

0    1000
1    1500
2    1600
Name: Salary, dtype: int64

In [82]:
data.loc[]

SyntaxError: invalid syntax (<ipython-input-82-e37d355f1092>, line 1)

In [85]:
data

names  EId  Salary
0   shr   12    1000
1   kvm   13    1500
2   chs   14    1600

In [50]:
data['present'] = [45,56,76]
data

names  EId  Salary  present
0   shr   12    1000       45
1   kvm   13    1500       56
2   chs   14    1600       76

In [51]:
data['absent'] = pd.Series([4,5,6])

In [52]:
data

names  EId  Salary  present  absent
0   shr   12    1000       45       4
1   kvm   13    1500       56       5
2   chs   14    1600       76       6

In [53]:
data['abc'] = pd.DataFrame([8,1,3])
data

names  EId  Salary  present  absent  abc
0   shr   12    1000       45       4    8
1   kvm   13    1500       56       5    1
2   chs   14    1600       76       6    3

In [86]:
data.index

RangeIndex(start=0, stop=3, step=1)

In [89]:
data1 = data.copy()

In [90]:
data1

names  EId  Salary
0   shr   12    1000
1   kvm   13    1500
2   chs   14    1600

In [91]:
data1

names  EId  Salary
0   shr   12    1000
1   kvm   13    1500
2   chs   14    1600

In [92]:
import pandas as pd
df1 = pd.DataFrame({'col1': [1,2], 'col2':[3,4]})
print(df1)

   col1  col2
0     1     3
1     2     4


In [95]:
df2 = pd.DataFrame({'col1': [5,6], 'col2':[7,8]})
print(df2)

   col1  col2
0     5     7
1     6     8


In [96]:
df = df1.append(df2)
df

col1  col2
0     1     3
1     2     4
0     5     7
1     6     8

In [99]:
df = pd.concat([df1,df2])
df

col1  col2
0     1     3
1     2     4
0     5     7
1     6     8

In [100]:
data

names  EId  Salary
0   shr   12    1000
1   kvm   13    1500
2   chs   14    1600

In [62]:
data.iloc[1,2]

1500

In [63]:
data

names  EId  Salary  present  absent  abc
0   shr   12    1000       45       4    8
1   kvm   13    1500       56       5    1
2   chs   14    1600       76       6    3

In [101]:
data.describe()

EId       Salary
count   3.0     3.000000
mean   13.0  1366.666667
std     1.0   321.455025
min    12.0  1000.000000
25%    12.5  1250.000000
50%    13.0  1500.000000
75%    13.5  1550.000000
max    14.0  1600.000000

In [102]:
data

names  EId  Salary
0   shr   12    1000
1   kvm   13    1500
2   chs   14    1600

In [156]:
data.iloc[0:2,2:4]

Salary  present
0    1000        8
1    1500        1

In [157]:
data

names  EId  Salary  present  absent  abc
0   shr   12    1000        8       4    8
1   kvm   13    1500        1       5    1
2   chs   14    1600        3       6    3

In [103]:
data.head()

names  EId  Salary
0   shr   12    1000
1   kvm   13    1500
2   chs   14    1600

In [104]:
data.tail()

names  EId  Salary
0   shr   12    1000
1   kvm   13    1500
2   chs   14    1600

In [112]:
data

names  EId  Salary
0   shr   12    1000
1   kvm   13    1500
2   chs   14    1600

In [64]:
data.loc[0, 'Salary']

1000

In [109]:
def half(h):
    return h/2

In [110]:
data

names  EId  Salary
0   shr   12    1000
1   kvm   13    1500
2   chs   14    1600

In [111]:
data[['Salary','absent']].apply(half)

KeyError: "['absent'] not in index"

In [106]:
def double(d):
    return d*2

In [66]:
data

names  EId  Salary  present  absent  abc
0   shr   12    1000       45       4    8
1   kvm   13    1500       56       5    1
2   chs   14    1600       76       6    3

In [67]:
data['present'].apply(double)

0     90
1    112
2    152
Name: present, dtype: int64

In [113]:
data['names'].value_counts()

shr    1
chs    1
kvm    1
Name: names, dtype: int64

In [151]:
data['present'].sort_values()

KeyError: 'present'

In [115]:
data

names  EId  Salary
0   shr   12    1000
1   kvm   13    1500
2   chs   14    1600

In [116]:
data.sort_values(by ='Salary')

names  EId  Salary
0   shr   12    1000
1   kvm   13    1500
2   chs   14    1600

In [117]:
data

names  EId  Salary
0   shr   12    1000
1   kvm   13    1500
2   chs   14    1600

In [118]:
import os

In [119]:
os.getcwd()

'F:\\anaconda\\self practice'

In [135]:
WSD = pd.read_csv(r"F:\anaconda\data sets\RetailScoreData.csv")
WSD.head()

branch  ncust  customer  age  ed  employ  address  income  debtinc  \
0       3   3017     10012   28   2       7        2      44     17.7   
1       3   3017     10017   64   5      34       17     116     14.7   
2       3   3017     10030   40   1      20       12      61      4.8   
3       3   3017     10039   30   1      11        3      27     34.5   
4       3   3017     10069   25   1       2        2      30     22.4   

   creddebt  othdebt  default  
0      2.99     4.80        0  
1      5.05    12.00        0  
2      1.04     1.89        0  
3      1.75     7.56        0  
4      0.76     5.96        1

In [136]:
a = pd.read_csv(r"F:\anaconda\data sets\RetailScoreData.csv")
a.head()

branch  ncust  customer  age  ed  employ  address  income  debtinc  \
0       3   3017     10012   28   2       7        2      44     17.7   
1       3   3017     10017   64   5      34       17     116     14.7   
2       3   3017     10030   40   1      20       12      61      4.8   
3       3   3017     10039   30   1      11        3      27     34.5   
4       3   3017     10069   25   1       2        2      30     22.4   

   creddebt  othdebt  default  
0      2.99     4.80        0  
1      5.05    12.00        0  
2      1.04     1.89        0  
3      1.75     7.56        0  
4      0.76     5.96        1

In [137]:
wsd=pd.read_csv(r"F:\anaconda\data sets\RetailScoreData.csv")
wsd.head()

branch  ncust  customer  age  ed  employ  address  income  debtinc  \
0       3   3017     10012   28   2       7        2      44     17.7   
1       3   3017     10017   64   5      34       17     116     14.7   
2       3   3017     10030   40   1      20       12      61      4.8   
3       3   3017     10039   30   1      11        3      27     34.5   
4       3   3017     10069   25   1       2        2      30     22.4   

   creddebt  othdebt  default  
0      2.99     4.80        0  
1      5.05    12.00        0  
2      1.04     1.89        0  
3      1.75     7.56        0  
4      0.76     5.96        1

In [189]:
wsd.tail()

branch  ncust  customer  age  ed  employ  address  income  debtinc  \
1495      91   3779    453471   34   3       8        4      83     11.0   
1496      91   3779    453578   37   2      10        8      43      3.6   
1497      91   3779    453686   25   5       0        3      16      3.2   
1498      91   3779    453698   34   1      10        8      41     14.5   
1499      91   3779    453777   27   1       2        2      24      5.8   

      creddebt  othdebt  default  
1495      1.85     7.28        0  
1496      0.81     0.74        0  
1497      0.29     0.22        0  
1498      1.19     4.75        0  
1499      0.56     0.84        0

In [191]:
wsd.sort_values(by='income')

branch  ncust  customer  age  ed  employ  address  income  debtinc  \
70         3   3017     11859   18   2       0        0      12      8.2   
259       15   4809     72584   18   2       0        0      12      3.3   
1482      91   3779    453082   20   3       0        0      13     17.8   
1395      77   2251    382157   20   3       0        0      13      0.0   
1194      75   2600    372485   20   3       0        0      13      1.1   
...      ...    ...       ...  ...  ..     ...      ...     ...      ...   
776       64   1919    316502   51   4      20       18     512      6.5   
1435      91   3779    451171   34   5       8        7     526      2.6   
1461      91   3779    452132   59   2      32       19     533      0.8   
468       25   3491    122365   62   5      31       14     699      5.9   
1198      75   2600    372551   57   5      31       23    1079      1.4   

      creddebt  othdebt  default  
70        0.15     0.83        1  
259       0.11     0.29        1  
1482      0.81     1.50        0  
1395      0.00     0.00        0  
1194      0.05     0.09        0  
...        ...      ...      ...  
776       6.82    26.46        0  
1435      5.47     8.21        0  
1461      1.86     2.40        0  
468       6.60    34.64        0  
1198      1.96    13.14        0  

[1500 rows x 12 columns]

In [198]:
wsd.describe()

branch        ncust       customer          age           ed  \
count  1500.000000  1500.000000    1500.000000  1500.000000  1500.000000   
mean     52.200000  3478.066667  257714.548000    34.174000     2.639333   
std      27.928719   864.710980  139555.147719    13.142306     1.144025   
min       3.000000  1919.000000   10012.000000    18.000000     1.000000   
25%      20.000000  2658.000000   98638.750000    24.000000     2.000000   
50%      64.000000  3491.000000  315991.500000    31.000000     2.000000   
75%      75.000000  4358.000000  370701.500000    42.000000     4.000000   
max      91.000000  4809.000000  453777.000000    79.000000     5.000000   

            employ      address       income      debtinc     creddebt  \
count  1500.000000  1500.000000  1500.000000  1500.000000  1500.000000   
mean      6.952000     6.305333    59.588667     9.929333     1.934913   
std       8.977644     6.047740    67.130160     6.671884     2.973909   
min       0.000000     0.000000    12.000000     0.000000     0.000000   
25%       0.000000     2.000000    27.000000     4.800000     0.420000   
50%       4.000000     5.000000    40.000000     8.500000     0.990000   
75%      10.000000     9.000000    64.000000    13.525000     2.200000   
max      63.000000    34.000000  1079.000000    40.700000    35.970000   

           othdebt      default  
count  1500.000000  1500.000000  
mean      3.844327     0.365333  
std       5.333425     0.481684  
min       0.000000     0.000000  
25%       1.107500     0.000000  
50%       2.215000     0.000000  
75%       4.572500     1.000000  
max      63.470000     1.000000

In [199]:
wsd.sort_index()

branch  ncust  customer  age  ed  employ  address  income  debtinc  \
0          3   3017     10012   28   2       7        2      44     17.7   
1          3   3017     10017   64   5      34       17     116     14.7   
2          3   3017     10030   40   1      20       12      61      4.8   
3          3   3017     10039   30   1      11        3      27     34.5   
4          3   3017     10069   25   1       2        2      30     22.4   
...      ...    ...       ...  ...  ..     ...      ...     ...      ...   
1495      91   3779    453471   34   3       8        4      83     11.0   
1496      91   3779    453578   37   2      10        8      43      3.6   
1497      91   3779    453686   25   5       0        3      16      3.2   
1498      91   3779    453698   34   1      10        8      41     14.5   
1499      91   3779    453777   27   1       2        2      24      5.8   

      creddebt  othdebt  default  
0         2.99     4.80        0  
1         5.05    12.00        0  
2         1.04     1.89        0  
3         1.75     7.56        0  
4         0.76     5.96        1  
...        ...      ...      ...  
1495      1.85     7.28        0  
1496      0.81     0.74        0  
1497      0.29     0.22        0  
1498      1.19     4.75        0  
1499      0.56     0.84        0  

[1500 rows x 12 columns]

In [200]:
wsd

branch  ncust  customer  age  ed  employ  address  income  debtinc  \
0          3   3017     10012   28   2       7        2      44     17.7   
1          3   3017     10017   64   5      34       17     116     14.7   
2          3   3017     10030   40   1      20       12      61      4.8   
3          3   3017     10039   30   1      11        3      27     34.5   
4          3   3017     10069   25   1       2        2      30     22.4   
...      ...    ...       ...  ...  ..     ...      ...     ...      ...   
1495      91   3779    453471   34   3       8        4      83     11.0   
1496      91   3779    453578   37   2      10        8      43      3.6   
1497      91   3779    453686   25   5       0        3      16      3.2   
1498      91   3779    453698   34   1      10        8      41     14.5   
1499      91   3779    453777   27   1       2        2      24      5.8   

      creddebt  othdebt  default  
0         2.99     4.80        0  
1         5.05    12.00        0  
2         1.04     1.89        0  
3         1.75     7.56        0  
4         0.76     5.96        1  
...        ...      ...      ...  
1495      1.85     7.28        0  
1496      0.81     0.74        0  
1497      0.29     0.22        0  
1498      1.19     4.75        0  
1499      0.56     0.84        0  

[1500 rows x 12 columns]

In [202]:
wsd.iloc[100:120,3]

100    46
101    36
102    45
103    59
104    35
105    62
106    29
107    56
108    24
109    32
110    25
111    37
112    27
113    56
114    31
115    59
116    65
117    26
118    27
119    30
Name: age, dtype: int64

In [203]:
wsd

branch  ncust  customer  age  ed  employ  address  income  debtinc  \
0          3   3017     10012   28   2       7        2      44     17.7   
1          3   3017     10017   64   5      34       17     116     14.7   
2          3   3017     10030   40   1      20       12      61      4.8   
3          3   3017     10039   30   1      11        3      27     34.5   
4          3   3017     10069   25   1       2        2      30     22.4   
...      ...    ...       ...  ...  ..     ...      ...     ...      ...   
1495      91   3779    453471   34   3       8        4      83     11.0   
1496      91   3779    453578   37   2      10        8      43      3.6   
1497      91   3779    453686   25   5       0        3      16      3.2   
1498      91   3779    453698   34   1      10        8      41     14.5   
1499      91   3779    453777   27   1       2        2      24      5.8   

      creddebt  othdebt  default  
0         2.99     4.80        0  
1         5.05    12.00        0  
2         1.04     1.89        0  
3         1.75     7.56        0  
4         0.76     5.96        1  
...        ...      ...      ...  
1495      1.85     7.28        0  
1496      0.81     0.74        0  
1497      0.29     0.22        0  
1498      1.19     4.75        0  
1499      0.56     0.84        0  

[1500 rows x 12 columns]

In [17]:
import pandas as pd

In [140]:
wss = pd.read_csv(r"F:\anaconda\data sets\Walmart_Store_sales.csv")
wss.head()

Store        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \
0      1  05-02-2010    1643690.90             0        42.31       2.572   
1      1  12-02-2010    1641957.44             1        38.51       2.548   
2      1  19-02-2010    1611968.17             0        39.93       2.514   
3      1  26-02-2010    1409727.59             0        46.63       2.561   
4      1  05-03-2010    1554806.68             0        46.50       2.625   

          CPI  Unemployment  
0  211.096358         8.106  
1  211.242170         8.106  
2  211.289143         8.106  
3  211.319643         8.106  
4  211.350143         8.106

In [81]:
df = wss.groupby(['Store']).sum()
df.head()

Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price           CPI  \
Store                                                                      
1      2.224028e+08            10      9767.87     460.417  30887.555523   
2      2.753824e+08            10      9754.94     460.417  30837.422420   
3      5.758674e+07            10     10215.09     460.417  31372.988971   
4      2.995440e+08            10      8902.23     460.027  18401.192733   
5      4.547569e+07            10      9925.65     460.417  30968.878137   

       Unemployment  
Store                
1          1088.290  
2          1090.210  
3          1026.309  
4           852.951  
5           900.243

In [105]:
df["Weekly_Sales"].idxmax()

20

In [123]:
sd = wss.groupby(["Store"]).std()
sd.head()

Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price       CPI  \
Store                                                                   
1      155980.767761      0.255926    14.250486    0.427313  4.350890   
2      237683.694682      0.255926    15.492766    0.427313  4.342286   
3       46319.631557      0.255926    12.645851    0.427313  4.434232   
4      266201.442297      0.255926    16.180023    0.416967  1.858300   
5       37737.965745      0.255926    14.225352    0.427313  4.364848   

       Unemployment  
Store                
1          0.383749  
2          0.615414  
3          0.447245  
4          1.421267  
5          0.387415

In [116]:
sd["Weekly_Sales"].idxmax()

14

In [4]:
import pandas as pd
import numpy as np

In [141]:
df = pd.read_csv(r'F:\anaconda\data sets\Walmart_Store_sales.csv')

In [142]:
df.head(2)

Store        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \
0      1  05-02-2010    1643690.90             0        42.31       2.572   
1      1  12-02-2010    1641957.44             1        38.51       2.548   

          CPI  Unemployment  
0  211.096358         8.106  
1  211.242170         8.106

In [143]:
df.shape

(6435, 8)

In [144]:
df.rename(columns = {"Store" : "Stores"}, inplace = True)

In [145]:
df.head(3)

Stores        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \
0       1  05-02-2010    1643690.90             0        42.31       2.572   
1       1  12-02-2010    1641957.44             1        38.51       2.548   
2       1  19-02-2010    1611968.17             0        39.93       2.514   

          CPI  Unemployment  
0  211.096358         8.106  
1  211.242170         8.106  
2  211.289143         8.106

In [146]:
df.columns

Index(['Stores', 'Date', 'Weekly_Sales', 'Holiday_Flag', 'Temperature',
       'Fuel_Price', 'CPI', 'Unemployment'],
      dtype='object')

In [147]:
df.columns = df.columns.str.replace("_" , " ")

In [148]:
df.columns

Index(['Stores', 'Date', 'Weekly Sales', 'Holiday Flag', 'Temperature',
       'Fuel Price', 'CPI', 'Unemployment'],
      dtype='object')

In [149]:
df.columns = df.columns.str.replace(" ", "_")

In [150]:
df.columns

Index(['Stores', 'Date', 'Weekly_Sales', 'Holiday_Flag', 'Temperature',
       'Fuel_Price', 'CPI', 'Unemployment'],
      dtype='object')

In [130]:
a = df.rename(columns = {"CPI" : "cpi"}).head(2)
a

Stores        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \
0       1  05-02-2010    1643690.90             0        42.31       2.572   
1       1  12-02-2010    1641957.44             1        38.51       2.548   

          cpi  Unemployment  
0  211.096358         8.106  
1  211.242170         8.106

In [131]:
a.columns = a.columns.str.replace("cpi", "CPI")

In [132]:
a

Stores        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \
0       1  05-02-2010    1643690.90             0        42.31       2.572   
1       1  12-02-2010    1641957.44             1        38.51       2.548   

          CPI  Unemployment  
0  211.096358         8.106  
1  211.242170         8.106

In [133]:
df.sort_values(by = "Weekly_Sales")

Stores        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \
4619      33  03-12-2010     209986.25             0        52.82       3.041   
4614      33  29-10-2010     213538.32             0        71.34       3.130   
4675      33  30-12-2011     215359.21             1        51.60       3.428   
4623      33  31-12-2010     219804.85             1        52.91       3.148   
4671      33  02-12-2011     220060.35             0        59.12       3.701   
...      ...         ...           ...           ...          ...         ...   
1762      13  24-12-2010    3595903.20             0        34.90       2.846   
527        4  23-12-2011    3676388.98             0        35.92       3.103   
1333      10  24-12-2010    3749057.69             0        57.06       3.236   
2763      20  24-12-2010    3766687.43             0        25.17       3.141   
1905      14  24-12-2010    3818686.45             0        30.59       3.141   

             CPI  Unemployment  
4619  126.731333         9.265  
4614  126.436419         9.265  
4675  130.071032         8.010  
4623  127.087677         9.265  
4671  129.845967         8.010  
...          ...           ...  
1762  126.983581         7.795  
527   129.984548         5.143  
1333  126.983581         9.003  
2763  204.637673         7.484  
1905  182.544590         8.724  

[6435 rows x 8 columns]

In [19]:
df.sort_values("Weekly_Sales", ascending=True).head()

Stores        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \
4619      33  03-12-2010     209986.25             0        52.82       3.041   
4614      33  29-10-2010     213538.32             0        71.34       3.130   
4675      33  30-12-2011     215359.21             1        51.60       3.428   
4623      33  31-12-2010     219804.85             1        52.91       3.148   
4671      33  02-12-2011     220060.35             0        59.12       3.701   

             CPI  Unemployment  
4619  126.731333         9.265  
4614  126.436419         9.265  
4675  130.071032         8.010  
4623  127.087677         9.265  
4671  129.845967         8.010

In [21]:
df.head()

Stores        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \
0       1  05-02-2010    1643690.90             0        42.31       2.572   
1       1  12-02-2010    1641957.44             1        38.51       2.548   
2       1  19-02-2010    1611968.17             0        39.93       2.514   
3       1  26-02-2010    1409727.59             0        46.63       2.561   
4       1  05-03-2010    1554806.68             0        46.50       2.625   

          CPI  Unemployment  
0  211.096358         8.106  
1  211.242170         8.106  
2  211.289143         8.106  
3  211.319643         8.106  
4  211.350143         8.106